apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-gateway/application.yaml
  - attack-worker/application.yaml
  - brain/application.yaml
  - dashboard/application.yaml
  - infrastructure/postgres/application.yaml
  - infrastructure/temporal/application.yaml
